### ISSUE TITLE
Install/Update 1.1.0-2 Fails on WeeWX 5.0.0a24

### ISSUE THREAD

**Issue by gary-hammer** [michael-slx/weewx-weatherlink-live#25]
I gave the new release a try as the last release (1.0.11) was working well in WeeWX 5 alphas.
I'm attaching the log from the attempt as wx5.txt

[wx5.txt](https://github.com/michael-slx/weewx-weatherlink-live/files/11129339/wx5.txt)

**Comment by michael-slx** [comment]
I didn't know there were v5 alphas. I'll have to look into it.

**Comment by gary-hammer** [comment]
I must have gotten lucky then with the last release.

**Comment by michael-slx** [comment]
I've just pushed a new commit updating the VM scripts.

I've tested the driver with v5 alpha and it seems to work now.

**Comment by gary-hammer** [comment]
Which alpha and driver version?

**Comment by michael-slx** [comment]
Driver v1.1, WeeWX directly from Github repo V5 branch

**Comment by gary-hammer** [comment]
Hmmm, fails to run here. It did install however.
Installing 1..0.11 works fine.

Attaching error log.
[wx-wll.txt](https://github.com/michael-slx/weewx-weatherlink-live/files/11183105/wx-wll.txt)

**Comment by gary-hammer** [comment]
It looks like it fails when there is an old driver installed.

**Comment by G400** [comment]
Current release (1.1.1) fails when installing in WeeWX  5.0.0b17

sudo weectl extension install weewx-weatherlink-live-v1.1.1.tar.xz
Request to install 'weewx-weatherlink-live-v1.1.1.tar.xz'.
Extracting from tar archive weewx-weatherlink-live-v1.1.1.tar.xz
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 112, in install_extension
    ext.install_extension(namespace.source)
  File "/usr/share/weewx/weecfg/extension.py", line 122, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
  File "/usr/share/weewx/weecfg/extension.py", line 154, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 201, in install_from_dir
    save_config |= self._inject_config(installer['config'], extension_name)
KeyError: 'config'

**Comment by JPAustinTX** [comment]
Using WeeWx 5.0.2

Release 1.1.2 following the install instructions does not install. Weewx seems to have changed many files and seems to be broken.

Eventually settled on the newer extension installer

> weectl extension install EXTENSION-LOCATION

This is what I see now using the following: 

> weectl extension list
Using configuration file /etc/weewx/weewx.conf
Extension Name    Version   Description
weatherlink-live  1.1.2     WeeWX driver for Davis WeatherLink Live.

So I think it's installed. 
 
> weectl station reconfigure
Only shows the default configurations. Not yours. Assuming the documentation is all wrong now and needs to be updated. 

My weewx.conf was modified to include the following: 
 ##############################################################################
[WeatherLinkLive]
    # Driver module
    driver = user.weatherlink_live_driver

    # Host name or IP address of WeatherLink Live
    host = MyIP_Address

    # Mapping of transmitter ids to WeeWX records
    mapping = th:1, rain:1, wind:1, windchill:1, thw:1:appTemp, battery:1:outTemp:rain:wind, th_indoor, baro

    # Whether to log successful operations.  Overrides top-level setting.
    #log_success = False

    # Whether to log unsuccessful operations. Overrides top-level setting.
    #log_failure = True

Yes it fails when I try to start weewx.
>sudo systemctl start weewx
>sudo systemctl status weewx

 Loaded: loaded (/etc/systemd/system/weewx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2024-02-11 15:00:25 CST; 14s ago
     Docs: https://weewx.com/docs
  Process: 2871 ExecStart=/usr/bin/weewxd /etc/weewx/weewx.conf (code=exited, status=1/FAILURE)
 Main PID: 2871 (code=exited, status=1/FAILURE)

Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****    File "/etc/weewx/bin/user/weatherlink_live/configuration.py", line 24, in
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****      from user.weatherlink_live.mappers import TMapping, THMapping, WindMappi
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****    File "/etc/weewx/bin/user/weatherlink_live/mappers.py", line 48, in <modul
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****      class AbstractMapping(object):
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****    File "/etc/weewx/bin/user/weatherlink_live/mappers.py", line 137, in Abstr
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****      def map_table(self) -> Dict[str, Union[str, list[str]]]:
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****  TypeError: 'type' object is not subscriptable
Feb 11 15:00:25 pi weewxd[2871]: CRITICAL __main__:     ****  Exiting.
Feb 11 15:00:25 pi systemd[1]: weewx.service: Main process exited, code=exited, status=1/FAILURE
Feb 11 15:00:25 pi systemd[1]: weewx.service: Failed with result 'exit-code'.

**Comment by gary-hammer** [comment]
I just installed today.
All is fine with weewx 5.0.2 and 1.1.2
I used the pip install method and activated the venv
You don't mention if you are upgrading or what OS.

**Comment by gary-hammer** [comment]
Newer releases of both drivers and weewx
