### ISSUE TITLE
Question concerning historical data

### ISSUE THREAD

**Issue by gnipp** [michael-slx/weewx-weatherlink-live#8]
"WeatherLink Live currently does not provide a local API to access historic data" - just to get it right: There is unlimited access to historical data via weewx, right?
Background: due to current issues with the usb interface of the raspi, I'm considering to switch to the live interface but I will certainly not subscribe to Davis pages.
Thank you in advance for your answer and - for your development!
wetter.nipp.de

**Comment by michael-slx** [comment]
Yes, you'll of course still have access to your historic data via WeeWX.

In practice, this limitation only applies if WeeWX fails, e.g. because the power went out. In your current setup the data logger itself would continue recording and WeeWX can download these records when normal operation resumes. While the WeatherLink Live does have data logging capabilities it only sends that data to the WeatherLink.com site.
